# This is a sample Circle CI configuration file
# It assumes that you have a Netlify account and a site ID
# It also assumes that you have a netlify.toml file in your repository root
# For more details, please refer to https://circleci.com/docs/ and https://docs.netlify.com/

version: 2.1
orbs:
   node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: medium # Use the latest Ubuntu image
    
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - checkout # Checkout the code from the repository
      - run: # Install the Netlify CLI
          name: Install Netlify CLI
          command: npm install -g netlify-cli
      - run: 
          name: Netlify Init 
          command: netilfy init
      - run: # Build the site using the netlify.toml file
          name: Build site
          command: netlify build
      - run: # Deploy the site to Netlify pages
          name: Deploy site
          command: netlify deploy --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
          # You need to set the NETLIFY_SITE_ID and NETLIFY_AUTH_TOKEN as environment variables in Circle CI
workflows:
  build_and_deploy:
    jobs:
      - build # Run the build job on every push to the repository
